application:
  name: "Market Data Extractor"
  version: "1.0.0"
  description: "Market Data Extractor is a Python application that extracts market data from various sources and processes it for analysis and storage."
  environment: "development"
  debug: true

extractor_settings:
  client: "Upstox"
  interval: 1
  max_retries: 3
  retry_delay: 5
  processable_segments:
    - "NSE_INDEX"
    - "NSE_FO"
    - "BSE_INDEX"
    - "BSE_FO"
    - "MCX_FO"
  start_date: "2026-08-11"
  end_date: "2026-08-11"