application:
  name: "Market Data Extractor"
  version: "1.0.0"
  description: "Market Data Extractor is a Python application that extracts market data from various sources and processes it for analysis and storage."
  environment: "development"
  debug: true

extractor_settings:
  client: "Upstox"
  interval: 1
  max_retries: 3
  expiry_duration: 3
  processable_segments:
    - "NSE_INDEX"
    - "NSE_FO"
    - "BSE_INDEX"
    - "BSE_FO"
    - "MCX_FO"
  start_date: ""
  end_date: ""

transformation_settings:
  spot_name_mapping:
    "NIFTY FIN SERVICE": "FINNIFTY"
    "NIFTY 50": "NIFTY50"
    "Nifty50": "NIFTY50"
    "INDIA VIX": "VIX"
    "IndiaVix": "VIX"
    "NIFTY BANK": "BANKNIFTY"
    "BankNifty": "BANKNIFTY"
    "Banknifty": "BANKNIFTY"
    "BSE BANKEX": "BANKEX"
    "BSEBANKEX": "BANKEX"
    "BSE SENSEX": "SENSEX"
    "BSESENSEX": "SENSEX"

  session_bounds:
    indices:
      start: "09:15"
      end: "15:40"
    fno:
      start: "09:15"
      end: "15:40"
    equity:
      start: "09:15"
      end: "15:40"
    mcx:
      start: "09:15"
      end: "23:30"